### ISSUE TITLE
kill all fish does not work that way I want 

### ISSUE THREAD

**Issue by Suston** [Adamekka/fish#1]
This shitty fish config is gay cuz i want to kill all my terminals and I can cuz this nigga in not able to make a good fish config and I want to rape his asshole for this 
![image (3)](https://github.com/user-attachments/assets/27f87ccc-7d55-4e20-ad62-21827428f908)

**Comment by Adamekka** [comment]
Hello Suston,

I don't care.

Thank you for your understanding.

**Comment by Suston** [comment]
> Hello Suston,
> 
> I don't care.
> 
![image (1)](https://github.com/user-attachments/assets/75985829-6bc8-42ac-a2f3-694403c2c9e0)

> Thank you for your understanding.

**Comment by Suston** [comment]
![image (2)](https://github.com/user-attachments/assets/9b7b2886-f49f-43d0-b251-2e01c0e1b830)

**Comment by Suston** [comment]
![ezgif-1-daadc3161b](https://github.com/user-attachments/assets/3f2c9631-ab03-41b0-ac87-d6ea27774416)
